### ISSUE TITLE
FractalCircleWidget

### ISSUE THREAD

**Issue by AlexisCnockaert** [pharo-graphics/CoypuIDE#10]
- Fait/Tests solides
- Sert a Domenico pour representer des paramètres/effets (du genre delay/attack..)

**Comment by AlexisCnockaert** [comment]
<img width="452" alt="Capture d’écran 2024-05-15 à 13 16 30" src="https://github.com/pharo-graphics/CoypuIDE/assets/156106880/4104a85a-a2a7-4e9e-88df-d92dca75e85c">

**Comment by Ducasse** [comment]
Nice on pourra voir a mettre une echelle de couleur pour renforcer l'effet

**Comment by AlexisCnockaert** [comment]
> Nice on pourra voir a mettre une echelle de couleur pour renforcer l'effet

Je propose ca comme échelle de couleur, je trouve ca très esthétique 
<img width="452" alt="Capture d’écran 2024-05-17 à 11 29 13" src="https://github.com/pharo-graphics/CoypuIDE/assets/156106880/49350d27-e287-485f-be54-bdb54536d4bf">
