### ISSUE TITLE
Slider Widget

### ISSUE THREAD

**Issue by Enzo-Demeulenaere** [pharo-graphics/CoypuIDE#12]
* Fait avec tests
* horizontal ou vertical 
* segmenté ou non 
  * changeable dynamiquement
  * En définissant une step value
  * En définissant les valeurs des segmentations

Pas vraiment "skinnable" puisque fait sans utilisation de Toplo

<img width="526" alt="Capture d’écran 2024-05-15 à 14 20 02" src="https://github.com/pharo-graphics/CoypuIDE/assets/121249182/9ef366aa-f914-4cf9-bac6-c4d421c621b2">

**Comment by Ducasse** [comment]
Neat.

**Comment by tinchodias** [comment]
This slider looks nice. I have to try it. 

https://github.com/pharo-graphics/CoypuIDE/blob/master/CoypuIDE/ICSlider.class.st

We may port to Toplo and then use it on Spec-Toplo
