### ISSUE TITLE
"Axis" widget

### ISSUE THREAD

**Issue by Enzo-Demeulenaere** [pharo-graphics/CoypuIDE#13]
* Fait (sans tests)
* Récupération des 2 valeurs x et y 
* Label changeables (mais pas placés selon la taille du texte)

<img width="570" alt="Capture d’écran 2024-05-15 à 14 16 29" src="https://github.com/pharo-graphics/CoypuIDE/assets/121249182/a1058832-c829-469b-b70f-2cdf18d11fc7">

**Comment by lucretiomsp** [comment]
nice !
